// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 Aristocles <https://github.com/Aristocles>
// scripts/lib/demo-cards.js
//
// Pure, deterministic generators for the demo seed. Consumed by:
//   - scripts/seed-demo.js (the CLI/auto-seed entrypoint)
//   - tests/seed-demo.test.js (verifies generated output)
//
// Every `buildXxx()` function returns a valid klebb.datafile.v1 manifest
// object. The set of dates generated is anchored to a "today" reference
// passed in — the caller decides whether that's `new Date()` (live seed)
// or a fixed date (reproducible tests).
//
// Random values are generated by a seeded PRNG so identical inputs produce
// identical output. This makes the seed deterministic per install date
// (useful: tests are stable; visually the data always looks the same if
// you re-seed on the same day).

'use strict';

// ---------------------------------------------------------------------------
// Seeded PRNG — mulberry32, good-enough for demo data. Deterministic,
// reproducible, no external dependency.
// ---------------------------------------------------------------------------
function makeRng(seed) {
  let a = seed >>> 0;
  return function() {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function rngInt(rng, min, max) {
  return Math.floor(rng() * (max - min + 1)) + min;
}

function rngFloat(rng, min, max) {
  return rng() * (max - min) + min;
}

function rngPick(rng, arr) {
  return arr[Math.floor(rng() * arr.length)];
}

// ---------------------------------------------------------------------------
// Date helpers
// ---------------------------------------------------------------------------
function iso(d) {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${y}-${m}-${day}`;
}

function addDays(d, n) {
  const out = new Date(d);
  out.setDate(out.getDate() + n);
  return out;
}

// Last N days ending at `today`, oldest first.
function lastNDays(today, n) {
  const out = [];
  for (let i = n - 1; i >= 0; i--) out.push(addDays(today, -i));
  return out;
}

function utcIso(d, hour) {
  const h = hour ?? 8;
  const dt = new Date(Date.UTC(d.getFullYear(), d.getMonth(), d.getDate(), h, 0, 0));
  return dt.toISOString();
}

// ---------------------------------------------------------------------------
// Markdown-doc cards (welcome + how-to)
// ---------------------------------------------------------------------------
function buildWelcome() {
  const markdown = [
    '## 🎭 Welcome — this is demo data',
    '',
    'Your new Klebb install auto-populated itself with **15 sample cards** and **5 sample markdown reports** so you can see what the dashboard looks like before you build your own.',
    '',
    '**Nothing on this dashboard is real.** The weight graph, blood pressure readings, sleep hours, medication check-offs — all fabricated by the seed script. Poke around, then clear it and make it yours.',
    '',
    '### Poke around',
    '',
    '- **Today** — this page. Every card shows the most recent generated entry.',
    '- **Trends** — 30 days of data per metric card, plotted as line charts.',
    '- **Calendar** — heatmap of activity across every card that opts in.',
    '- **Reports** — cards with `meta.reports.enabled` plus five sample markdown docs in `$HEALTH_HOME/reports/`.',
    '- **Settings (⚙️)** — toggle any card off, or delete the data directly on disk.',
    '',
    '### Make it yours',
    '',
    '1. **Ask the chat agent** (🧠 button, bottom of screen). Say *"Add a card for tracking morning glucose"*. It drafts the manifest, drops the file in, restarts the registry. Card appears.',
    '2. **Copy an example.** The repo\'s `data.example/` directory has 25 ready-made card files. Copy one to `$HEALTH_HOME/data/`, drop the `.example` from the filename.',
    '3. **Write one by hand.** See `MANIFEST-SCHEMA.md` + `docs/CARDS.md` + `docs/RECIPES.md` in the repo.',
    '',
    '### Clear the demo',
    '',
    'When you\'re ready for your own data, either:',
    '',
    '- Delete individual cards in **Settings** (toggles them off; the files stay).',
    '- Or `rm $HEALTH_HOME/data/*.json $HEALTH_HOME/reports/*.md` and restart. The demo will **not** re-seed — a `.klebb-seeded` sentinel in `$HEALTH_HOME` records that the one-time seed has already run.',
    '',
    '---',
    '',
    '*Every card here is a JSON file. Drop a file in, a card appears. Delete the file, the card is gone. That is the entire app.*'
  ].join('\n');

  return {
    $schema: 'klebb.datafile.v1',
    meta: {
      id: 'welcome',
      label: 'Welcome — demo instance',
      emoji: '🎭',
      order: -100,
      view: {
        enabled: true,
        component: 'markdown-doc',
        slot: 'top'
      }
    },
    description: 'Demo-instance welcome card. Explains this is auto-seeded demo data.',
    data: { markdown }
  };
}

function buildHowToAddACard() {
  const markdown = [
    '## 📘 Adding your own cards',
    '',
    'Every card on this dashboard is a JSON file in `$HEALTH_HOME/data/`.',
    '',
    '### Three ways',
    '',
    '1. **Ask the chat agent.** Tap 🧠, say *"Add a card for tracking daily meditation minutes"*. It drafts the manifest, drops the file in, and the card appears.',
    '2. **Copy an example.** Browse `data.example/` in the repo — 25 ready-made cards. Copy the one you want to `$HEALTH_HOME/data/` and drop the `.example` from the filename.',
    '3. **Write one by hand.** Full spec: `MANIFEST-SCHEMA.md`. Patterns: `docs/CARDS.md`. Recipes: `docs/RECIPES.md`.',
    '',
    '### Removing a card',
    '',
    'Delete the file, or toggle it off in **Settings** (keeps the data, hides the card).',
    '',
    '### Getting help',
    '',
    'Ask the chat agent: *"Change the mood card to allow multiple entries per day"* or *"Why isn\'t my new card showing up?"*. It has access to the same docs you do.',
    '',
    '---',
    '',
    '*This is the **demo** how-to — the data around it is fake. Ready to build your own dashboard? See the welcome card above.*'
  ].join('\n');

  return {
    $schema: 'klebb.datafile.v1',
    meta: {
      id: 'how-to-add-a-card',
      label: 'How to add a card',
      emoji: '📘',
      order: -90,
      view: {
        enabled: true,
        component: 'markdown-doc',
        slot: 'top'
      }
    },
    description: 'Inline quick-reference for card authoring.',
    data: { markdown }
  };
}

// ---------------------------------------------------------------------------
// Metric cards — generic-card, pre-populated
// ---------------------------------------------------------------------------
function buildWeight(today, rng) {
  const days = lastNDays(today, 30);
  const data = [];
  let kg = 84.5;
  for (const d of days) {
    kg += rngFloat(rng, -0.3, 0.3);
    data.push({ date: iso(d), kg: Math.round(kg * 10) / 10, note: '' });
  }
  return {
    $schema: 'klebb.datafile.v1',
    meta: {
      id: 'weight',
      label: 'Weight',
      emoji: '⚖️',
      category: 'vitals',
      order: 20,
      description: 'Demo: body weight, 30 days of generated data.',
      view: {
        enabled: true,
        component: 'generic-card',
        dateContext: 'viewedDate',
        display: {
          template: '{kg}',
          unit: 'kg',
          subtitle: 'Logged {date}',
          secondary: '{note|}',
          emptyHeadline: 'No weight logged',
          trendArrow: { field: 'kg' }
        }
      },
      trends: {
        enabled: true,
        component: 'line-chart',
        title: 'Weight',
        xAxis: 'date',
        series: [{ field: 'kg', label: 'kg' }],
        yAxisLabel: 'kg'
      },
      reports: { enabled: true, component: 'markdown-doc' },
      writeable: {
        fromWebapp: true,
        pastAllowed: true,
        todayAllowed: true,
        futureAllowed: false,
        maxReadingsPerDay: 1,
        inputs: [
          { key: 'kg', type: 'number', label: 'Weight (kg)', min: 0, max: 500, step: 0.1, required: true },
          { key: 'note', type: 'text', label: 'Note', placeholder: 'optional' }
        ]
      }
    },
    data
  };
}

function buildBP(today, rng) {
  const days = lastNDays(today, 30);
  const data = days.map(d => ({
    date: iso(d),
    systolic: rngInt(rng, 115, 135),
    diastolic: rngInt(rng, 72, 88),
    hr: rngInt(rng, 58, 72),
    notes: ''
  }));
  return {
    $schema: 'klebb.datafile.v1',
    meta: {
      id: 'bp',
      label: 'Blood Pressure',
      emoji: '💓',
      category: 'vitals',
      order: 30,
      description: 'Demo: blood pressure, 30 days of generated data.',
      view: {
        enabled: true,
        component: 'generic-card',
        dateContext: 'viewedDate',
        display: {
          template: '{systolic}/{diastolic}',
          unit: 'mmHg',
          subtitle: 'Logged {date}',
          secondary: '{notes|}',
          emptyHeadline: 'No BP logged',
          thresholds: [
            { ifField: 'systolic', max: 119, colour: '#44ff88', label: 'Optimal' },
            { ifField: 'systolic', max: 129, colour: '#aaaa44', label: 'Elevated' },
            { ifField: 'systolic', max: 139, colour: '#ff7733', label: 'Stage 1' },
            { ifField: 'systolic', max: 999, colour: '#ff3333', label: 'Stage 2' }
          ]
        }
      },
      trends: {
        enabled: true,
        component: 'line-chart',
        title: 'Blood pressure',
        xAxis: 'date',
        series: [
          { field: 'systolic', label: 'Systolic' },
          { field: 'diastolic', label: 'Diastolic' }
        ],
        yAxisLabel: 'mmHg'
      },
      reports: { enabled: true, component: 'markdown-doc' },
      writeable: {
        fromWebapp: true,
        pastAllowed: true,
        todayAllowed: true,
        futureAllowed: false,
        maxReadingsPerDay: 3,
        inputs: [
          { key: 'systolic', type: 'number', label: 'Systolic (top)', min: 50, max: 250, step: 1, required: true },
          { key: 'diastolic', type: 'number', label: 'Diastolic (bottom)', min: 30, max: 200, step: 1, required: true },
          { key: 'hr', type: 'number', label: 'Heart rate (bpm)', min: 30, max: 220, step: 1 },
          { key: 'notes', type: 'text', label: 'Notes', placeholder: 'optional' }
        ]
      }
    },
    data
  };
}

function buildMood(today, rng) {
  const days = lastNDays(today, 30);
  const moodWeights = [2, 3, 3, 4, 4, 4, 5];
  const noteOptions = ['', '', '', 'solid sleep', 'busy day', 'felt flat', 'good energy'];
  const data = days.map(d => ({
    date: iso(d),
    mood: rngPick(rng, moodWeights),
    wakeUps: rngInt(rng, 0, 3),
    notes: rngPick(rng, noteOptions)
  }));
  return {
    $schema: 'klebb.datafile.v1',
    meta: {
      id: 'mood',
      label: 'Mood',
      emoji: '🙂',
      order: 60,
      description: 'Demo: daily mood check-in, 1-5 scale with emoji picker.',
      view: {
        enabled: true,
        component: 'generic-card',
        dateContext: 'viewedDate',
        display: {
          template: '{mood:emoji}',
          secondary: '{wakeUps|0} wake-ups · {notes|}',
          emptyHeadline: 'How are you feeling?',
          emojiMap: {
            mood: { '1': '😩', '2': '😴', '3': '😐', '4': '🙂', '5': '😄' }
          }
        }
      },
      trends: {
        enabled: true,
        component: 'line-chart',
        title: 'Mood (1-5)',
        xAxis: 'date',
        series: [{ field: 'mood', label: 'Mood' }],
        yAxisLabel: 'score'
      },
      reports: { enabled: true, component: 'markdown-doc' },
      prompt: { enabled: false, mode: 'modal', whenMissing: true },
      writeable: {
        fromWebapp: true,
        pastAllowed: true,
        todayAllowed: true,
        futureAllowed: false,
        maxReadingsPerDay: 1,
        inputs: [
          {
            key: 'mood', type: 'emoji-picker', label: 'Mood',
            emojis: ['😩', '😴', '😐', '🙂', '😄'],
            emitIndex: true, required: true, autoSubmit: true
          },
          { key: 'wakeUps', type: 'stepper', label: 'Wake-ups', min: 0, max: 20, default: 0 },
          { key: 'notes', type: 'textarea', label: 'Notes', rows: 2, placeholder: 'optional' }
        ]
      }
    },
    data
  };
}

function buildSleepHours(today, rng) {
  const days = lastNDays(today, 30);
  const data = days.map(d => ({
    date: iso(d),
    hours: Math.round(rngFloat(rng, 6.0, 8.5) * 4) / 4,
    quality: rngInt(rng, 2, 5)
  }));
  return {
    $schema: 'klebb.datafile.v1',
    meta: {
      id: 'sleep-hours',
      label: 'Sleep',
      emoji: '😴',
      category: 'sleep',
      order: 50,
      description: 'Demo: hours of sleep per night.',
      view: {
        enabled: true,
        component: 'generic-card',
        dateContext: 'viewedDate',
        display: {
          template: '{hours}',
          unit: 'h',
          subtitle: 'Logged {date}',
          emptyHeadline: 'No sleep logged',
          trendArrow: { field: 'hours' }
        }
      },
      trends: {
        enabled: true,
        component: 'line-chart',
        title: 'Sleep duration',
        xAxis: 'date',
        series: [{ field: 'hours', label: 'Hours' }],
        yAxisLabel: 'hours',
        goalLine: 8
      },
      reports: { enabled: true, component: 'markdown-doc' },
      writeable: {
        fromWebapp: true,
        pastAllowed: true,
        todayAllowed: true,
        futureAllowed: false,
        maxReadingsPerDay: 1,
        inputs: [
          { key: 'hours', type: 'number', label: 'Hours slept', min: 0, max: 14, step: 0.25, required: true },
          { key: 'quality', type: 'rating', label: 'Quality (1-5)', min: 1, max: 5 }
        ]
      }
    },
    data
  };
}

function buildHydration(today, rng) {
  const days = lastNDays(today, 30);
  const data = days.map(d => ({ date: iso(d), glasses: rngInt(rng, 4, 10) }));
  return {
    $schema: 'klebb.datafile.v1',
    meta: {
      id: 'hydration',
      label: 'Hydration',
      emoji: '💧',
      order: 82,
      description: 'Demo: glasses of water per day. Stepper input.',
      view: {
        enabled: true,
        component: 'generic-card',
        dateContext: 'viewedDate',
        display: {
          template: '{glasses}',
          unit: 'glasses',
          emptyHeadline: 'Drink up!',
          thresholds: [
            { ifField: 'glasses', max: 3, colour: '#ff3333', label: 'Dry' },
            { ifField: 'glasses', min: 4, max: 6, colour: '#ff7733', label: 'Low' },
            { ifField: 'glasses', min: 7, max: 9, colour: '#66cc55', label: 'Good' },
            { ifField: 'glasses', min: 10, colour: '#44ff88', label: 'Well-watered' }
          ]
        }
      },
      writeable: {
        fromWebapp: true,
        todayAllowed: true,
        pastAllowed: true,
        futureAllowed: false,
        maxReadingsPerDay: 1,
        inputs: [
          { key: 'glasses', type: 'stepper', label: 'Glasses of water', min: 0, max: 30, step: 1, default: 0, required: true }
        ]
      }
    },
    data
  };
}

function buildSteps(today, rng) {
  const days = lastNDays(today, 30);
  const data = days.map(d => ({ date: iso(d), steps: rngInt(rng, 3000, 14000) }));
  return {
    $schema: 'klebb.datafile.v1',
    meta: {
      id: 'steps',
      label: 'Steps',
      emoji: '👣',
      category: 'activity',
      order: 70,
      description: 'Demo: daily step count.',
      view: {
        enabled: true,
        component: 'generic-card',
        dateContext: 'viewedDate',
        display: {
          template: '{steps}',
          unit: 'steps',
          subtitle: 'Logged {date}',
          emptyHeadline: 'No steps logged',
          thresholds: [
            { ifField: 'steps', max: 4999, colour: '#ff7733', label: 'Low' },
            { ifField: 'steps', min: 5000, max: 9999, colour: '#aaaa44', label: 'Moderate' },
            { ifField: 'steps', min: 10000, colour: '#44ff88', label: 'Active' }
          ]
        }
      },
      trends: {
        enabled: true,
        component: 'line-chart',
        title: 'Steps',
        xAxis: 'date',
        series: [{ field: 'steps', label: 'Steps' }],
        yAxisLabel: 'steps',
        goalLine: 10000
      },
      writeable: {
        fromWebapp: true,
        todayAllowed: true,
        pastAllowed: true,
        futureAllowed: false,
        maxReadingsPerDay: 1,
        inputs: [
          { key: 'steps', type: 'number', label: 'Steps', min: 0, max: 100000, step: 1, required: true }
        ]
      }
    },
    data
  };
}

function buildCaffeine(today, rng) {
  const days = lastNDays(today, 30);
  const options = [0, 80, 150, 160, 200, 250, 300, 150, 200];
  const data = days.map(d => ({ date: iso(d), mg: rngPick(rng, options) }));
  return {
    $schema: 'klebb.datafile.v1',
    meta: {
      id: 'caffeine',
      label: 'Caffeine',
      emoji: '☕',
      order: 74,
      description: 'Demo: daily caffeine intake in mg.',
      view: {
        enabled: true,
        component: 'generic-card',
        dateContext: 'viewedDate',
        display: {
          template: '{mg}',
          unit: 'mg',
          emptyHeadline: 'No caffeine logged',
          thresholds: [
            { ifField: 'mg', max: 200, colour: '#66cc55', label: 'Moderate' },
            { ifField: 'mg', min: 201, max: 400, colour: '#aaaa44', label: 'High' },
            { ifField: 'mg', min: 401, colour: '#ff3333', label: 'Very high' }
          ]
        }
      },
      trends: {
        enabled: true,
        component: 'line-chart',
        title: 'Caffeine (mg)',
        xAxis: 'date',
        series: [{ field: 'mg', label: 'mg' }],
        yAxisLabel: 'mg'
      },
      writeable: {
        fromWebapp: true,
        todayAllowed: true,
        pastAllowed: true,
        futureAllowed: false,
        maxReadingsPerDay: 1,
        inputs: [
          { key: 'mg', type: 'number', label: 'Caffeine (mg)', min: 0, max: 2000, step: 10, required: true }
        ]
      }
    },
    data
  };
}

function buildEnergy(today, rng) {
  const days = lastNDays(today, 30);
  const data = days.map(d => ({ date: iso(d), level: rngInt(rng, 2, 5) }));
  return {
    $schema: 'klebb.datafile.v1',
    meta: {
      id: 'energy',
      label: 'Energy',
      emoji: '⚡',
      order: 62,
      description: 'Demo: daily energy on a 1-5 rating.',
      view: {
        enabled: true,
        component: 'generic-card',
        dateContext: 'viewedDate',
        display: {
          template: '{level}',
          unit: '/5',
          emptyHeadline: "How's your energy today?"
        }
      },
      writeable: {
        fromWebapp: true,
        todayAllowed: true,
        pastAllowed: true,
        futureAllowed: false,
        maxReadingsPerDay: 1,
        inputs: [
          { key: 'level', type: 'rating', label: 'Energy', min: 1, max: 5, required: true }
        ]
      }
    },
    data
  };
}

function buildRestingHR(today, rng) {
  const days = lastNDays(today, 30);
  const data = days.map(d => ({ date: iso(d), bpm: rngInt(rng, 52, 68) }));
  return {
    $schema: 'klebb.datafile.v1',
    meta: {
      id: 'heart-rate-resting',
      label: 'Resting HR',
      emoji: '❤️',
      category: 'vitals',
      order: 32,
      description: 'Demo: resting heart rate.',
      view: {
        enabled: true,
        component: 'generic-card',
        dateContext: 'viewedDate',
        display: {
          template: '{bpm}',
          unit: 'bpm',
          emptyHeadline: 'No RHR logged',
          trendArrow: { field: 'bpm', goodDirection: 'down' }
        }
      },
      trends: {
        enabled: true,
        component: 'line-chart',
        title: 'Resting heart rate',
        xAxis: 'date',
        series: [{ field: 'bpm', label: 'bpm' }],
        yAxisLabel: 'bpm'
      },
      reports: { enabled: true, component: 'markdown-doc' },
      writeable: {
        fromWebapp: true,
        todayAllowed: true,
        pastAllowed: true,
        futureAllowed: false,
        maxReadingsPerDay: 1,
        inputs: [
          { key: 'bpm', type: 'number', label: 'RHR (bpm)', min: 30, max: 220, step: 1, required: true }
        ]
      }
    },
    data
  };
}

function buildReflections(today, rng) {
  const days = lastNDays(today, 30);
  const samples = [
    'Productive morning. Shipped the refactor.',
    'Low energy all afternoon. Maybe the late coffee.',
    'Great walk along the headland at sunset.',
    "Couldn't focus. Took a nap, came back sharper.",
    'Long call with family. Felt grounded after.',
    "Started that book I'd been putting off.",
    'Trained legs. Brutal but satisfying.',
    'Slept badly. Pushed through with two coffees.',
    'Tried the new Thai place, worth it.',
    'Quiet day. Read and went to bed early.'
  ];
  const data = [];
  for (const d of days) {
    if (rng() < 0.6) {
      data.push({ date: iso(d), text: rngPick(rng, samples) });
    }
  }
  return {
    $schema: 'klebb.datafile.v1',
    meta: {
      id: 'reflections',
      label: 'Daily reflection',
      emoji: '📝',
      order: 90,
      description: 'Demo: free-form daily journal entry.',
      view: {
        enabled: true,
        component: 'generic-card',
        dateContext: 'viewedDate',
        display: {
          template: '{text|—}',
          emptyHeadline: "Today's thought?"
        }
      },
      reports: { enabled: true, component: 'markdown-doc' },
      writeable: {
        fromWebapp: true,
        todayAllowed: true,
        pastAllowed: true,
        futureAllowed: false,
        maxReadingsPerDay: 1,
        inputs: [
          { key: 'text', type: 'textarea', label: 'Reflection', rows: 4, placeholder: "What's on your mind?" }
        ]
      }
    },
    data
  };
}

// ---------------------------------------------------------------------------
// Non-generic renderers: list-card, checklist-card
// ---------------------------------------------------------------------------
function buildSymptoms(today) {
  // Timestamps relative to today so the roster looks current
  const makeCreated = daysAgo => utcIso(addDays(today, -daysAgo));
  return {
    $schema: 'klebb.datafile.v1',
    meta: {
      id: 'symptoms',
      label: 'Symptoms watchlist',
      emoji: '🩹',
      order: 85,
      description: 'Demo: persistent roster of symptoms being monitored.',
      view: {
        enabled: true,
        component: 'list-card',
        display: {
          primaryField: 'symptom',
          secondaryTemplate: '{severity|} {location|}',
          emptyMessage: 'No symptoms — tap Edit to add one.',
          maxCharPreview: 60
        }
      },
      writeable: {
        fromWebapp: true,
        inputs: [
          { key: 'symptom', type: 'text', label: 'Symptom', required: true, maxLength: 120 },
          { key: 'severity', type: 'rating', label: 'Severity (1-5)', min: 1, max: 5 },
          { key: 'location', type: 'text', label: 'Location', maxLength: 80 },
          { key: 'note', type: 'textarea', label: 'Note', rows: 3, maxLength: 500 }
        ]
      }
    },
    data: {
      items: [
        {
          id: 'sym-1',
          symptom: 'Right shoulder ache',
          severity: 2,
          location: 'deltoid insertion',
          note: 'Worse after desk days. Stretching helps. Demo entry.',
          createdAt: makeCreated(23)
        },
        {
          id: 'sym-2',
          symptom: 'Afternoon brain fog',
          severity: 3,
          location: '',
          note: 'Between 14:00 and 16:00 most days. Tracking caffeine overlap. Demo entry.',
          createdAt: makeCreated(14)
        },
        {
          id: 'sym-3',
          symptom: 'Seasonal sinus',
          severity: 1,
          location: 'forehead',
          note: 'Clears with saline rinse. Demo entry.',
          createdAt: makeCreated(6)
        }
      ]
    }
  };
}

function buildMedications(today, rng) {
  const days = lastNDays(today, 30);
  const genDoses = (adherence, filterFn) => {
    const out = [];
    for (const d of days) {
      if (filterFn && !filterFn(d)) continue;
      if (rng() < adherence) {
        out.push({ scheduledDate: iso(d), takenAt: utcIso(d, 8) });
      }
    }
    return out;
  };
  const mwf = d => [1, 3, 5].includes(d.getDay()); // Mon(1) Wed(3) Fri(5)

  const cycleStart = iso(addDays(today, -60));
  const cycleEnd = iso(addDays(today, 180));

  return {
    $schema: 'klebb.datafile.v1',
    meta: {
      id: 'medications',
      label: 'Medications & supplements',
      emoji: '💊',
      category: 'health',
      order: 40,
      description: 'Demo: scheduled daily medications and supplements.',
      view: {
        enabled: true,
        component: 'checklist-card',
        dateContext: 'exact-date'
      },
      reports: {
        enabled: true,
        component: 'adherence-report',
        showCompliance: true,
        showInventory: false
      },
      calendar: {
        enabled: true,
        component: 'day-marker',
        marker: '💊'
      },
      writeable: {
        fromWebapp: true,
        pastAllowed: true,
        todayAllowed: true,
        futureAllowed: false
      }
    },
    data: {
      groups: [
        { id: 'morning', label: 'Morning routine', items: ['omega-3', 'vitamin-d'] },
        { id: 'evening', label: 'Evening routine', items: ['magnesium'] }
      ],
      items: [
        {
          name: 'omega-3',
          display_name: 'Omega-3 fish oil',
          dose: '2 softgels (2g EPA/DHA)',
          timing: 'with breakfast',
          schedule: { type: 'daily', times_per_day: 1 },
          cycles: [{ type: 'on', start: cycleStart, end: cycleEnd }],
          doses: genDoses(0.90)
        },
        {
          name: 'vitamin-d',
          display_name: 'Vitamin D3',
          dose: '5000 IU',
          timing: 'morning',
          schedule: { type: 'weekly', on_days: ['Mon', 'Wed', 'Fri'] },
          cycles: [{ type: 'on', start: cycleStart, end: cycleEnd }],
          doses: genDoses(0.85, mwf)
        },
        {
          name: 'magnesium',
          display_name: 'Magnesium glycinate',
          dose: '400 mg',
          timing: 'before bed',
          schedule: { type: 'daily', times_per_day: 1 },
          cycles: [{ type: 'on', start: cycleStart, end: cycleEnd }],
          doses: genDoses(0.80)
        }
      ]
    }
  };
}

function buildHabits(today, rng) {
  const days = lastNDays(today, 30);
  const pickDates = adherence => days.filter(() => rng() < adherence).map(iso);

  const cycleStart = iso(addDays(today, -60));
  const cycleEnd = iso(addDays(today, 180));

  return {
    $schema: 'klebb.datafile.v1',
    meta: {
      id: 'habits',
      label: 'Daily habits',
      emoji: '🎯',
      order: 80,
      description: 'Demo: daily habit checklist.',
      view: {
        enabled: true,
        component: 'checklist-card',
        dateContext: 'exact-date'
      },
      writeable: {
        fromWebapp: true,
        pastAllowed: true,
        todayAllowed: true,
        futureAllowed: false
      }
    },
    data: {
      items: [
        {
          name: 'meditate',
          display_name: '10-min meditation',
          schedule: { type: 'daily', times_per_day: 1 },
          cycles: [{ type: 'on', start: cycleStart, end: cycleEnd }],
          takenDates: pickDates(0.70)
        },
        {
          name: 'read',
          display_name: 'Read 20 pages',
          schedule: { type: 'daily', times_per_day: 1 },
          cycles: [{ type: 'on', start: cycleStart, end: cycleEnd }],
          takenDates: pickDates(0.55)
        },
        {
          name: 'walk',
          display_name: 'Walk outside',
          schedule: { type: 'daily', times_per_day: 1 },
          cycles: [{ type: 'on', start: cycleStart, end: cycleEnd }],
          takenDates: pickDates(0.80)
        },
        {
          name: 'no-phone-in-bed',
          display_name: 'No phone in bed',
          schedule: { type: 'daily', times_per_day: 1 },
          cycles: [{ type: 'on', start: cycleStart, end: cycleEnd }],
          takenDates: pickDates(0.45)
        }
      ]
    }
  };
}

// ---------------------------------------------------------------------------
// Top-level generator — returns { cards: { filename: object, ... } }
// ---------------------------------------------------------------------------
function generateDemoCards({ today, seed } = {}) {
  const ref = today instanceof Date ? today : new Date();
  // Strip time — we want a pure date anchor.
  const refDate = new Date(ref.getFullYear(), ref.getMonth(), ref.getDate());
  const rngSeed = Number.isInteger(seed) ? seed : 0xc0ffee;
  const rng = makeRng(rngSeed);

  return {
    'welcome.json': buildWelcome(),
    'how-to-add-a-card.json': buildHowToAddACard(),
    'weight.json': buildWeight(refDate, rng),
    'bp.json': buildBP(refDate, rng),
    'mood.json': buildMood(refDate, rng),
    'sleep-hours.json': buildSleepHours(refDate, rng),
    'hydration.json': buildHydration(refDate, rng),
    'steps.json': buildSteps(refDate, rng),
    'caffeine.json': buildCaffeine(refDate, rng),
    'energy.json': buildEnergy(refDate, rng),
    'heart-rate-resting.json': buildRestingHR(refDate, rng),
    'reflections.json': buildReflections(refDate, rng),
    'symptoms.json': buildSymptoms(refDate),
    'medications.json': buildMedications(refDate, rng),
    'habits.json': buildHabits(refDate, rng)
  };
}

module.exports = {
  generateDemoCards,
  // Exposed for tests
  _internal: { makeRng, iso, addDays, lastNDays }
};
